Chore
kmu-alphabeta/milipreview-backend pull request #17
Opened 2024-11-22 06:30 UTC by cg10036

1. 회원가입 제거
2. form에 group 추가
3. 점수 계산 추가
4. form 관련해서 타입 지정

form 관련해서 변동 사항 있으니 (group) 확인 부탁드립니다.

swagger 작성 부탁드립니다!

2024-11-22 07:00 UTC, sinam7 requested changes
일단 로그인부터 빠르게 고쳐줄래?

2024-11-22 07:04 UTC, cg10036 commented on src/auth/auth.service.ts
> +
아 npm run sync 해볼래?

2024-11-22 07:06 UTC, cg10036 commented on src/additional-form/additional-form.service.ts
> +
calculate로 한게, 우리 수정을 최소화 하기 위해서 그냥 프론트에서 점수 계산된 값 받고 여기로 넘기려고 했는데, 조금 이상한 것 같으면 수정해도 돼

2024-11-22 07:07 UTC, sinam7 commented on src/auth/auth.service.ts
> +
```
[Nest] 26720  - 2024. 11. 22. 오후 4:06:50   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'getPrimaryKey')
```

2024-11-22 07:11 UTC, sinam7 commented on src/additional-form/additional-form.service.ts
> +
그럼 플로우가 어떻게 되는거지?
1. FE에서 `/form/calculate` 요청
2. `calculate` 다 돌아가면 컨트롤러 단에서 `PredictionController.getPrediction()`  호출
3. 해당 결과 FE에게 리턴
인가?

이게 맞다면, 2번에서 저 메소드를 호출하기 위해 위에 언급한 `PredictionRequestDto`에 값을 넣어야 하는데, 
1. 계산 결과를 어떻게 포매팅해서 넣을 것인지
2. 그에 앞서 저 dto 포맷이 모델에 들어가는 형태가 맞는지 + 예시로 Json 하나 보여줄 수 있는지
를 확인해야 해.

2024-11-22 07:20 UTC, cg10036 commented on src/auth/auth.service.ts
> +
완료!

2024-11-22 07:40 UTC, JuYeobOh commented on src/additional-form/additional-form.service.ts
> +
모델 입력값은 지원하려는 년, 월,  카테고리, 점수 이렇게 보내줘야 하고 
response는 합격예측컷, "합격/불합격" string, 합격할 확률 이렇게 return 하도록 설계했는데 어떻게 수정하면 될까요?

2024-11-22 07:43 UTC, sinam7 commented on src/additional-form/additional-form.service.ts
> +
> 모델 입력값은 지원하려는 년, 월, 카테고리, 점수 이렇게 보내줘야 하고 response는 합격예측컷, "합격/불합격" string, 합격할 확률 이렇게 return 하도록 설계했는데 어떻게 수정하면 될까요?

그렇다면 dto는 수정할 필요 없고, 저 `AdditionalFormController.calculate()` 호출이 끝나고 점수 `final`이 나오면, 이걸 가지고 `PredictionController.getPrediction()` 수행 가능하도록 그 사이를 이어주면 될거야.

2024-11-23 01:52 UTC, sinam7 approved these changes

2024-11-23 01:53 UTC, merged